version: '3'
services:
  db:
     image: mysql
     container_name: mysql_db1
     restart: always
     environment:
        - MYSQL_ROOT_PASSWORD="secret"
  web:
    image: apache
    build: .
    depends_on:
       - db
    container_name: apache_web1
    restart: always
    ports:
      - "800:80"
